spring:
  application:
    name: Task4-BankAccount

  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: ${SPRING_DATASOURCE_DRIVER_CLASS_NAME}

  jpa:
    database-platform: ${SPRING_JPA_DATABASE_PLATFORM}
    hibernate:
      ddl-auto: ${SPRING_JPA_HIBERNATE_DDL_AUTO}
    show-sql: ${SPRING_JPA_SHOW_SQL}
    properties:
      hibernate:
        format_sql: ${SPRING_JPA_PROPERTIES_HIBERNATE_FORMAT_SQL}
    open-in-view: false

  sql:
    init:
      mode: ${SPRING_SQL_INIT_MODE}
      schema-locations: ${SPRING_SQL_INIT_SCHEMA_LOCATIONS}

server:
  servlet:
    context-path: ${SERVER_SERVLET_CONTEXT_PATH}
  port: ${SERVER_PORT}


